spring:
  thymeleaf:
    prefix: classpath:/templates/
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/epes?useUnicode=true&characterEncoding=utf-8
    username: group3
    password: 123456
  redis:
    host: localhost
    port: 6379
    timeout: 0
#    redis 连接使用默认
      # REDIS (RedisProperties)
      # Redis数据库索引（默认为0）
#      spring.redis.database=0
#      # Redis服务器地址
#      spring.redis.host=192.168.0.58
#      # Redis服务器连接端口
#      spring.redis.port=6379
#      # Redis服务器连接密码（默认为空）
#      spring.redis.password=
#      # 连接池最大连接数（使用负值表示没有限制）
#      spring.redis.pool.max-active=8
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      spring.redis.pool.max-wait=-1
#      # 连接池中的最大空闲连接
#      spring.redis.pool.max-idle=8
#      # 连接池中的最小空闲连接
#      spring.redis.pool.min-idle=0
#      # 连接超时时间（毫秒）
#      spring.redis.timeout=0

mybatis:
  type-aliases-package: com.epes.demo.entity

logging:
  level:
    root: info
    com:
      epes:
        demo:
          dao: debug
    org:
      mybatis: warn
      springframework:
        web: info
  path: /output/logger/

