spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/epes?useUnicode=true&characterEncoding=utf-8
    username: group3
    password: 123456
mybatis:
  type-aliases-package: com.epes.demo.entity

logging:
  level:
    root: info
    com:
      epes:
        demo:
          dao: debug
    org:
      mybatis: warn
      springframework:
        web: info
  path: /output/logger/